
package com.studentInfo;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Saimon Islam
 */
public class AddNewCourse extends javax.swing.JFrame {

    Connection sqlConn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    int q, i, id, deleteItem;
    public String stid;

    /**
     * Creates new form ChangeUserPass
     */
    public AddNewCourse() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        confirmBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        durationAdd = new javax.swing.JTextField();
        courseNameAdd = new javax.swing.JTextField();
        teacherNameAdd = new javax.swing.JTextField();
        feeAdd = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(128, 184, 231));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        confirmBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        confirmBtn.setText("Add Course");
        confirmBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmBtnActionPerformed(evt);
            }
        });
        jPanel1.add(confirmBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 350, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Course Name:");
        jLabel2.setToolTipText("");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 110, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Teacher's Name:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, 110, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Duration:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 110, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Fee:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 110, 30));
        jPanel1.add(durationAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, 180, 30));
        jPanel1.add(courseNameAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, 180, 30));
        jPanel1.add(teacherNameAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, 180, 30));
        jPanel1.add(feeAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, 180, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 844, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void confirmBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmBtnActionPerformed

        if(feeAdd.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Fee should not be empty");
        }else if(teacherNameAdd.getText().equals("")){
             JOptionPane.showMessageDialog(null, "Techar's Name should not be empty");
        }else if(durationAdd.getText().equals("")){
             JOptionPane.showMessageDialog(null, "Duration Name should not be empty");
        }else if(courseNameAdd.getText().equals("")){
             JOptionPane.showMessageDialog(null, "Course Name should not be empty");
        }
        String courseName = null;
        String fee = feeAdd.getText();
        String teacherName = teacherNameAdd.getText();
        courseName = courseNameAdd.getText();
        String duration = durationAdd.getText();
        LoginPage l = new LoginPage();
        try (Connection conn = l.connect()) {
//            pst = conn.prepareStatement("select * from user");
//            rs = pst.executeQuery();
//            ResultSetMetaData StData = rs.getMetaData();
//            q = StData.getColumnCount();
//            while (rs.next()) {
//                for (i = 1; i <= q; i++) {
//                    usern = rs.getString("username");
//                    pass = rs.getString("password");
//                }
//
//            }
            if (courseName != null) {
                String insertCourse  = "INSERT INTO course(course_name,duration,fee,teacher_name,action_date) SELECT " + "'" + courseName + "'" + "," + "'" + duration + "'" + "," + "'" + fee + "'" + "," + "'" + teacherName + "'" + ",LOCALTIME()\n" +
                            "WHERE " + "'" + courseName + "'" + " not in(SELECT course_name from course) or (SELECT course_name from course) is null";
                pst = conn.prepareStatement(insertCourse);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(this, "Course Added");
//                feeUpd.setText(null);
//                teacherNameUpd.setText(null);
            } else {
//                feeUpd.setText(null);
//                teacherNameUpd.setText(null);
                JOptionPane.showMessageDialog(null, "Course name should not be empty");
            }

        } catch (SQLException e) {
            e.printStackTrace();
        }


    }//GEN-LAST:event_confirmBtnActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ChangePass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ChangePass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ChangePass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ChangePass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ChangePass().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton confirmBtn;
    private javax.swing.JTextField courseNameAdd;
    private javax.swing.JTextField durationAdd;
    private javax.swing.JTextField feeAdd;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField teacherNameAdd;
    // End of variables declaration//GEN-END:variables
}
