/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.studentInfo;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

import java.sql.*;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import java.text.DateFormat;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.Vector;
/**
 *
 * @author azizul.islam
 */
public class SearchResultWindow extends javax.swing.JFrame {

    /**
     * Creates new form SearchResultWindow
     */
    Connection sqlConn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    int q, i, id, deleteItem;
    public String stid;
    public SearchResultWindow(String studentId) {
        stid = studentId;
        System.out.println("enrollSearchBox >> "+ stid);
        initComponents();
        studentSearch(stid);
    }
    public void studentSearch(String studentId) {
        LoginPage loginPage = new LoginPage();
        try (Connection conn = loginPage.connect()) {
//            enrollSearchBox        
            EnrollStudents es = new EnrollStudents();
            es.enrollSearchBox.getText();
            
//            e1.enrollSearchBtn.getText();
            pst = conn.prepareStatement("select * from student where studentid = " + "'" + stid + "'");
            rs = pst.executeQuery();
            ResultSetMetaData StData = rs.getMetaData();
            q = StData.getColumnCount();
            DefaultTableModel RecordTable = (DefaultTableModel) jTable1.getModel();
            RecordTable.setRowCount(0);
            while (rs.next()) {

                Vector columnData = new Vector();

                for (i = 1; i <= q; i++) {
//                    columnData.add(rs.getInt("id"));
                    columnData.add(rs.getString("studentid"));
                    columnData.add(rs.getString("studentname"));
                    columnData.add(rs.getString("batch"));
                    columnData.add(rs.getString("address"));
                    columnData.add(rs.getString("gender"));
                    columnData.add(rs.getString("mobile"));
//                    columnData.add(rs.getString("date"));
                    columnData.add(rs.getString("bloodgroup"));
                    columnData.add(rs.getString("coursename"));
                    columnData.add(rs.getString("coursefee"));
//                    columnData.add(rs.getString("duration"));
                    columnData.add(rs.getString("paidamount"));
                    columnData.add(rs.getString("dueamount"));
                    columnData.add(rs.getString("status"));
                }
                RecordTable.addRow(columnData);

            }
//            total.setText("" + RecordTable.getRowCount() + "");

        } catch (SQLException e) {
            e.printStackTrace();
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(195, 224, 252));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(195, 224, 252));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setBackground(new java.awt.Color(223, 240, 250));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student ID", "Name", "Batch", "Address", "Gender", "Mobile", "Date", "Blood Group", "Course Name", "Course Fee", "Duration", "Paid", "Due", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 397));

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 403, 69, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 440));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

        DefaultTableModel RecordTable = (DefaultTableModel) jTable1.getModel();
        int SelectedRows = jTable1.getSelectedRow();

//        studentId.setText(RecordTable.getValueAt(SelectedRows, 0).toString());
//        studentName.setText(RecordTable.getValueAt(SelectedRows, 1).toString());
//        batch.setText(RecordTable.getValueAt(SelectedRows, 2).toString());
//        address.setText(RecordTable.getValueAt(SelectedRows, 3).toString());
//        gender.setSelectedItem(RecordTable.getValueAt(SelectedRows, 4).toString());
//        mobile.setText(RecordTable.getValueAt(SelectedRows, 5).toString());
//        startDate.setText(RecordTable.getValueAt(SelectedRows, 6).toString());
//        bloodGroup.setText(RecordTable.getValueAt(SelectedRows, 7).toString());
//        course.setSelectedItem(RecordTable.getValueAt(SelectedRows, 8).toString());
//        courseFee.setText(RecordTable.getValueAt(SelectedRows, 9).toString());
//        duration.setText(RecordTable.getValueAt(SelectedRows, 10).toString());
//        paidAmount.setText(RecordTable.getValueAt(SelectedRows, 11).toString());
//        dueAmount.setText(RecordTable.getValueAt(SelectedRows, 12).toString());
//        status.setSelectedItem(RecordTable.getValueAt(SelectedRows, 13).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        EnrollStudents enst = new EnrollStudents();
        enst.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(SearchResultWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(SearchResultWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(SearchResultWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(SearchResultWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new SearchResultWindow("").setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
